vm:
        box: aws

        hostname: master

        network:
            private_network: 192.168.56.101
            forwarded_port: {  }

        provider:
            aws:
                keypair_name: polycliniqueborinage
                ami: ami-f1810f86
                region: eu-west-1
                instance_type: t1.micro
                security_groups: sg-5d12f439
                subnet_id: subnet-03a2225a
                elastic_ip: 
                tags:
                    Source: Ansible
        synced_folder:
            appointment-api:
                source: /Users/targoo/Sites/polycliniqueborinage/appointment-api
                target: /var/www/appointment-api
                owner: vagrant
                group: www-data
            appointment-app:
                source: /Users/targoo/Sites/polycliniqueborinage/appointment-app
                target: /var/www/appointment-app
                owner: vagrant
                group: www-data
            poly:
                source: /Users/targoo/Sites/polycliniqueborinage/poly
                target: /var/www/poly
                owner: vagrant
                group: www-data
            polygone:
                source: /Users/targoo/Sites/polycliniqueborinage/polygone
                target: /var/www/polygone
                owner: vagrant
                group: www-data
            protocol:
                source: /Users/targoo/Sites/polycliniqueborinage/protocol
                target: /var/www/protocol
                owner: vagrant
                group: www-data
            drupal7:
                source: /Users/targoo/Sites/polycliniqueborinage/drupal7
                target: /var/www/drupal7
                owner: vagrant
                group: www-data
            drupal8:
                source: /Users/targoo/Sites/polycliniqueborinage/drupal8
                target: /var/www/drupal8
                owner: vagrant
                group: www-data
            api:
                source: /Users/targoo/Sites/polycliniqueborinage/appointment-app
                target: /var/www/appointment-app
                owner: vagrant
                group: www-data
            db_backup:
                source: /Users/targoo/Sites/polycliniqueborinage/db_backup
                target: /var/backups/db_backup
                owner: vagrant
                group: www-data

ssh:
        host: null
        port: null
        private_key_path: ~/.ssh/polycliniqueborinage.pem
        username: ubuntu
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'


# Vagrant.
vagrant_user: vagrant


# You can configure almost anything else on the server in the rest of this file.
extra_security_enabled: true


# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, make set this value to an empty set, e.g. `[]`.
installed_extras:
  - redis
  # - adminer
  # - mailhog
  # - memcached
  # - pimpmylog
  # - selenium
  # - solr
  # - varnish
  # - xdebug
  # - xhprof


# Drupal Configuration.
drupal_major_version: 8


# PHP Configuration.
# Currently-supported versions: 5.5, 5.6, 7.0 (experimental).
php_version: "5.5"
php_memory_limit: "192M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/ssmtp -t"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"


# MySQL Configuration.
mysql_root_password: azerty2007-89
mysql_slow_query_log_enabled: true
mysql_slow_query_time: 2
mysql_wait_timeout: 300
adminer_add_apache_config: true

# MySQL Databases and users. If build_from_makefile is true, first database will
# be used for the makefile-built site.
mysql_databases:
  - name: "drupal"
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: "drupal"
    host: "%"
    password: "drupal"
    priv: "drupal.*:ALL"


# Apache
# Apache VirtualHosts. Add one for each site you are running inside the VM. For
# multisite deployments, you can point multiple servernames at one documentroot.
apache_vhosts:
  - {servername: "www.polycliniqueborinage.com", documentroot: "/var/www/drupal"}
  - {servername: "api.polycliniqueborinage.com", documentroot: "/var/www/api/www"}
  - {servername: "ionic.polycliniqueborinage.com", documentroot: "/var/www/ionic"}
apache_remove_default_vhost: true
apache_mods_enabled:
  - expires.load
  - ssl.load
  - rewrite.load
